from PatternFunc import *

playPattern("ExampleSound")

"""
playPattern(0)
playPattern(1)
playPattern(2)
playPattern(3)
playPattern(4)
playPattern(5)
playPattern(6)
playPattern(6)
playPattern(7)
playPattern(7)
playPattern(8)
playPattern(10)
playPattern(11)
playPattern(12)
playPattern(13)
playPattern(7)
playPattern(14)
playPattern(8)
playPattern(15)
playPattern(16)
playPattern(17)
playPattern(18)
playPattern(19)
playPattern(20)
playPattern(7)
playPattern(14)
playPattern(9)
playPattern(21)
"""